kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "bank-transaction" 
spec:
  runPolicy: "Serial" 
  triggers: 
    - type: "ImageChange"
    - type: ConfigChange
  source: 
    git:
      uri: "https://github.com/PakornPK/bank-transaction.git"
  strategy: 
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output: 
    to:
      kind: "ImageStreamTag"
      name: "bank-transaction:latest"
